### ISSUE TITLE
Wiring diagram to the pi zero

### ISSUE THREAD

**Issue by Alternating** [kellertk/pwnagotchi-plugin-gpsd#6]
I see that your power is gnd and 3.3v but which pins are the TX/RX going to? which are White and Grey respectively. I also had to download the gpsd-py3 manually https://pypi.org/project/gpsd-py3/#files and install manually as i ran into issues with name resolution for the provided link. I'm assuming this could have been avoided had I used a usb network adapter vs over bluetooth tethering.   To install locally - 
sudo tar -xvzf gpsd-py3-0.3.0.tar.gz
sudo pip install -e /home/pi/gpsd-py3-0.3.0/

**Comment by kellertk** [comment]
I haven't looked at this repository in a long time, but it's a serial port, so 
Power - 3v3 (or 5v, depends on your GPS)
GND - GND
TX - RX on the pi, pin 10
RX - TX on the pi, pin 8

Check out https://pinout.xyz/pinout/io_pi_zero

I'm sure the python gps libraries are a bit out of date as documented here. I'm glad you got it working.
